# Generated by Django 4.1.7 on 2023-02-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('debit', 'Debit')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
